---
address_entries_datacentre:
    global:
        - name: EXAMPLE.COM
          ip: 12.0.0.0
          mask: 24
        - name: EXAMPLE.DOMAIN.COM
          ip: 13.1.1.1          
          mask: 32
        - name: GOOGLE
          ip: "{{ lookup('dig', 'google.com') }}"
          mask: 32

address_groups_datacentre:
    global:
        - name: EXAMPLE_SERVERS
          address:
              - EXAMPLE.COM
              - EXAMPLE.DOMAIN.COM

firewall_policies_datacentre:
    global:
        - name: PUBLIC_SERVICES
          dst: EXAMPLE_SERVERS
          src: any
          from_zone: INTERNET
          to_zone: DMZ
          application:
              - junos-https
              - junos-http
              - junos-ping
          terminate_action: permit


custom_applications_datacentre:
    applications:
        ALT_HTTP:
            protocol: tcp
            dst_port: 8443


    multi_term_app:
        example_internal:
            fe_test:
                protocol: tcp
                dst_port: 15444
            fe_nginx:
                protocol: tcp
                dst_port: 1111

    app_sets:
        FE_INTERNAL:
            - ALT_HTTP
            - example_internal
